#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("com.achievements.android_v2.Resource", IsApplication=true)]

namespace com.achievements.android_v2
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Novell.MonoDroid.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int BadgeSheet_CloseButton = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int CategoriesBar_corner = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int close = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int facebook_icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int FirstBadge = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Login_background = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Login_background2 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Login_facebookbutton = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Login_logo = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int NavBar_background = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int NavBar_firstScreenButton = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int NavBar_globeb = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int NavBar_leftWindow = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int NavBar_ProfileButton = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int NavBar_secondScreenButton = 2130837518;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050018
			public const int BadgeImageView = 2131034136;
			
			// aapt resource value: 0x7f050008
			public const int BadgeSheetImageView = 2131034120;
			
			// aapt resource value: 0x7f050010
			public const int BadgeSheet_CloseImageButton = 2131034128;
			
			// aapt resource value: 0x7f05000f
			public const int BadgeSheet_CloseImageButtonFake = 2131034127;
			
			// aapt resource value: 0x7f050007
			public const int FirstBadgeFrontRelativeLayout = 2131034119;
			
			// aapt resource value: 0x7f05000a
			public const int FirstBadge_BadgeImageView = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int FirstBadge_GreenBonusImageView = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int FirstBadge_ProfileNameTextView = 2131034124;
			
			// aapt resource value: 0x7f050000
			public const int FristBadgeMainRelativeLayout = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int NavBar_AchievesCountTextView = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int NavBar_Globed'ImageView = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int NavBar_ImageButton = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int NavBar_LeftWinImageView = 2131034114;
			
			// aapt resource value: 0x7f050006
			public const int NavBar_ProfileScreenImageButton = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int NavBar_secondScreenImageButton = 2131034117;
			
			// aapt resource value: 0x7f050009
			public const int center = 2131034121;
			
			// aapt resource value: 0x7f050019
			public const int imageView1 = 2131034137;
			
			// aapt resource value: 0x7f050017
			public const int login = 2131034135;
			
			// aapt resource value: 0x7f050015
			public const int login_backgroundImageView = 2131034133;
			
			// aapt resource value: 0x7f050014
			public const int login_centerTextView = 2131034132;
			
			// aapt resource value: 0x7f050013
			public const int relativeLayout1 = 2131034131;
			
			// aapt resource value: 0x7f050016
			public const int signUpTextView = 2131034134;
			
			// aapt resource value: 0x7f05000d
			public const int textView1 = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int textView2 = 2131034126;
			
			// aapt resource value: 0x7f050011
			public const int textView3 = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int textView5 = 2131034130;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int FirstBadgeActivityLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int LoginActivityLayout = 2130903041;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
