#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("itsbeta.achievements.Resource", IsApplication=true)]

namespace itsbeta.achievements
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Novell.MonoDroid.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Categories_btn_arrow = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Categories_btn_divider = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Categories_btn_norm = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Categories_btn_press = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Categories_panel_check = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Categories_panel_divider = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int FakeAchivePic = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Icon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int itsbetabadge = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int line = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Login_background = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Login_background2 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int Login_Badge = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int Login_logo = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int NavBar_appLogo = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int NavBar_btn_edit = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int NavBar_btn_menu = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int Navigation_bar = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int Profile_Loginbutton = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int singInFacebook = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int Table_socialNetwork_BK_btn_norm = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int Table_socialNetwork_BK_btn_press = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int Table_socialNetwork_FB_btn_norm = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int Table_socialNetwork_FB_btn_press = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int Table_socialNetwork_TW_btn_norm = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int Table_socialNetwork_TW_btn_press = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int zdravoohranenie = 2130837530;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050027
			public const int AchiveDescriptionTextView = 2131034151;
			
			// aapt resource value: 0x7f050021
			public const int AchiveImageView = 2131034145;
			
			// aapt resource value: 0x7f050026
			public const int AchiveNameTextView = 2131034150;
			
			// aapt resource value: 0x7f050028
			public const int AchiveReceiveDateTextView = 2131034152;
			
			// aapt resource value: 0x7f05001d
			public const int AchivementsListView = 2131034141;
			
			// aapt resource value: 0x7f050002
			public const int BadgeImageView = 2131034114;
			
			// aapt resource value: 0x7f05001e
			public const int CategNameTextView = 2131034142;
			
			// aapt resource value: 0x7f05001f
			public const int CheckImageView = 2131034143;
			
			// aapt resource value: 0x7f050019
			public const int NavigationBarImageButton = 2131034137;
			
			// aapt resource value: 0x7f05001a
			public const int NavigationBarLogoImageView = 2131034138;
			
			// aapt resource value: 0x7f05001b
			public const int NavigationBarMenuImageButton = 2131034139;
			
			// aapt resource value: 0x7f050030
			public const int ProfileStatisticTitle = 2131034160;
			
			// aapt resource value: 0x7f05001c
			public const int SelectedCategoriesLinearLayout = 2131034140;
			
			// aapt resource value: 0x7f05002a
			public const int UserInfo = 2131034154;
			
			// aapt resource value: 0x7f050004
			public const int badgenameTextView = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int badgereadybutton = 2131034117;
			
			// aapt resource value: 0x7f05000e
			public const int badgestextView = 2131034126;
			
			// aapt resource value: 0x7f05000d
			public const int bonusInfoTextView = 2131034125;
			
			// aapt resource value: 0x7f05000c
			public const int bonustextView = 2131034124;
			
			// aapt resource value: 0x7f050006
			public const int butlineimageView = 2131034118;
			
			// aapt resource value: 0x7f050001
			public const int button = 2131034113;
			
			// aapt resource value: 0x7f05000b
			public const int categoryProjectInfoTextView = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int categoryProjectTextView = 2131034122;
			
			// aapt resource value: 0x7f050020
			public const int check_button = 2131034144;
			
			// aapt resource value: 0x7f050007
			public const int civ = 2131034119;
			
			// aapt resource value: 0x7f050022
			public const int facebook_button = 2131034146;
			
			// aapt resource value: 0x7f050008
			public const int howWasEarnDescrTextView = 2131034120;
			
			// aapt resource value: 0x7f050014
			public const int imageView1 = 2131034132;
			
			// aapt resource value: 0x7f050013
			public const int login = 2131034131;
			
			// aapt resource value: 0x7f050018
			public const int loginWebView = 2131034136;
			
			// aapt resource value: 0x7f050017
			public const int login_backgroundImageView = 2131034135;
			
			// aapt resource value: 0x7f050016
			public const int login_centerTextView = 2131034134;
			
			// aapt resource value: 0x7f05002e
			public const int logoutbutton = 2131034158;
			
			// aapt resource value: 0x7f05002b
			public const int pfacebook_button = 2131034155;
			
			// aapt resource value: 0x7f05002c
			public const int ptwitter_button = 2131034156;
			
			// aapt resource value: 0x7f05002d
			public const int pvk_button = 2131034157;
			
			// aapt resource value: 0x7f050000
			public const int relativeLayout1 = 2131034112;
			
			// aapt resource value: 0x7f050025
			public const int relativeLayout2 = 2131034149;
			
			// aapt resource value: 0x7f05002f
			public const int relativeLayout3 = 2131034159;
			
			// aapt resource value: 0x7f050012
			public const int signUpTextView = 2131034130;
			
			// aapt resource value: 0x7f05000f
			public const int textView1 = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int textView2 = 2131034128;
			
			// aapt resource value: 0x7f050009
			public const int textView3 = 2131034121;
			
			// aapt resource value: 0x7f050023
			public const int twitter_button = 2131034147;
			
			// aapt resource value: 0x7f050029
			public const int userName = 2131034153;
			
			// aapt resource value: 0x7f050011
			public const int usertextView = 2131034129;
			
			// aapt resource value: 0x7f050024
			public const int vk_button = 2131034148;
			
			// aapt resource value: 0x7f050015
			public const int webView1 = 2131034133;
			
			// aapt resource value: 0x7f050003
			public const int wonderHowtextView = 2131034115;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int BadgeListFrameLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int FirstBadgeLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int LoginActivityLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int LoginActivityWebLayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int LoginWebLayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int MainActivityLayout = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int MainLayoutCategoryDropDownListRow = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int MainLayoutListRow = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int ProfileActivityLayout = 2130903048;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f04003a
			public const int accessibility_delegate_button = 2130968634;
			
			// aapt resource value: 0x7f04003b
			public const int accessibility_delegate_custom_text_added = 2130968635;
			
			// aapt resource value: 0x7f040039
			public const int accessibility_delegate_instructions = 2130968633;
			
			// aapt resource value: 0x7f040038
			public const int accessibility_delegate_title = 2130968632;
			
			// aapt resource value: 0x7f040037
			public const int accessibility_manager_accessibility_state = 2130968631;
			
			// aapt resource value: 0x7f040036
			public const int accessibility_manager_enabled_service = 2130968630;
			
			// aapt resource value: 0x7f040034
			public const int accessibility_manager_instructions = 2130968628;
			
			// aapt resource value: 0x7f040035
			public const int accessibility_manager_no_enabled_services = 2130968629;
			
			// aapt resource value: 0x7f040033
			public const int accessibility_manager_title = 2130968627;
			
			// aapt resource value: 0x7f040000
			public const int activity_sample_code = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int alert_dialog_cancel = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int alert_dialog_ok = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int alert_dialog_two_buttons_title = 2130968578;
			
			// aapt resource value: 0x7f040007
			public const int corky = 2130968583;
			
			// aapt resource value: 0x7f040029
			public const int first = 2130968617;
			
			// aapt resource value: 0x7f04001e
			public const int fragment1menu = 2130968606;
			
			// aapt resource value: 0x7f04001f
			public const int fragment2menu = 2130968607;
			
			// aapt resource value: 0x7f04000b
			public const int fragment_alert_dialog_support = 2130968587;
			
			// aapt resource value: 0x7f04000e
			public const int fragment_arguments_embedded = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int fragment_arguments_embedded_land = 2130968591;
			
			// aapt resource value: 0x7f04000d
			public const int fragment_arguments_msg = 2130968589;
			
			// aapt resource value: 0x7f04000c
			public const int fragment_arguments_support = 2130968588;
			
			// aapt resource value: 0x7f040013
			public const int fragment_context_menu_msg = 2130968595;
			
			// aapt resource value: 0x7f040012
			public const int fragment_context_menu_support = 2130968594;
			
			// aapt resource value: 0x7f040010
			public const int fragment_custom_animation_support = 2130968592;
			
			// aapt resource value: 0x7f040019
			public const int fragment_dialog_or_activity_inline = 2130968601;
			
			// aapt resource value: 0x7f040018
			public const int fragment_dialog_or_activity_msg = 2130968600;
			
			// aapt resource value: 0x7f040017
			public const int fragment_dialog_or_activity_support = 2130968599;
			
			// aapt resource value: 0x7f040015
			public const int fragment_dialog_support = 2130968597;
			
			// aapt resource value: 0x7f040011
			public const int fragment_hide_show_support = 2130968593;
			
			// aapt resource value: 0x7f04001a
			public const int fragment_layout_support = 2130968602;
			
			// aapt resource value: 0x7f04001b
			public const int fragment_list_array_support = 2130968603;
			
			// aapt resource value: 0x7f04001d
			public const int fragment_menu_msg = 2130968605;
			
			// aapt resource value: 0x7f04001c
			public const int fragment_menu_support = 2130968604;
			
			// aapt resource value: 0x7f040028
			public const int fragment_pager_support = 2130968616;
			
			// aapt resource value: 0x7f040023
			public const int fragment_receive_result_support = 2130968611;
			
			// aapt resource value: 0x7f040021
			public const int fragment_retain_instance_msg = 2130968609;
			
			// aapt resource value: 0x7f040020
			public const int fragment_retain_instance_support = 2130968608;
			
			// aapt resource value: 0x7f040024
			public const int fragment_stack_support = 2130968612;
			
			// aapt resource value: 0x7f04002b
			public const int fragment_state_pager_support = 2130968619;
			
			// aapt resource value: 0x7f040026
			public const int fragment_tabs = 2130968614;
			
			// aapt resource value: 0x7f040027
			public const int fragment_tabs_pager = 2130968615;
			
			// aapt resource value: 0x7f040001
			public const int hello_world = 2130968577;
			
			// aapt resource value: 0x7f040005
			public const int initial_text = 2130968581;
			
			// aapt resource value: 0x7f04002a
			public const int last = 2130968618;
			
			// aapt resource value: 0x7f04002c
			public const int loader_cursor_support = 2130968620;
			
			// aapt resource value: 0x7f04002d
			public const int loader_custom_support = 2130968621;
			
			// aapt resource value: 0x7f04002e
			public const int loader_throttle_support = 2130968622;
			
			// aapt resource value: 0x7f04002f
			public const int local_service_broadcaster = 2130968623;
			
			// aapt resource value: 0x7f040030
			public const int local_service_broadcaster_msg = 2130968624;
			
			// aapt resource value: 0x7f040014
			public const int long_press = 2130968596;
			
			// aapt resource value: 0x7f040025
			public const int new_fragment = 2130968613;
			
			// aapt resource value: 0x7f040006
			public const int pick_result = 2130968582;
			
			// aapt resource value: 0x7f040009
			public const int receive_result_instructions = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int receive_result_result = 2130968586;
			
			// aapt resource value: 0x7f040022
			public const int restart = 2130968610;
			
			// aapt resource value: 0x7f040016
			public const int show = 2130968598;
			
			// aapt resource value: 0x7f040031
			public const int start_service = 2130968625;
			
			// aapt resource value: 0x7f040032
			public const int stop_service = 2130968626;
			
			// aapt resource value: 0x7f040008
			public const int violet = 2130968584;
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
