//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace itsbeta_wp7 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("itsbeta_wp7.Languages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Itsbeta - all your achieves in one application..
        /// </summary>
        public static string about_description {
            get {
                return ResourceManager.GetString("about_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About program.
        /// </summary>
        public static string about_program {
            get {
                return ResourceManager.GetString("about_program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About project:.
        /// </summary>
        public static string about_project {
            get {
                return ResourceManager.GetString("about_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version 1.0.
        /// </summary>
        public static string about_version {
            get {
                return ResourceManager.GetString("about_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to activate badge description.
        /// </summary>
        public static string activate_badge_description {
            get {
                return ResourceManager.GetString("activate_badge_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTIVATE BADGE.
        /// </summary>
        public static string activate_badge_title {
            get {
                return ResourceManager.GetString("activate_badge_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to activation.
        /// </summary>
        public static string activation {
            get {
                return ResourceManager.GetString("activation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Badges:.
        /// </summary>
        public static string all_badges {
            get {
                return ResourceManager.GetString("all_badges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  opened.
        /// </summary>
        public static string badges_opened_label {
            get {
                return ResourceManager.GetString("badges_opened_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bonus.
        /// </summary>
        public static string bonus {
            get {
                return ResourceManager.GetString("bonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonuses:.
        /// </summary>
        public static string bonuses {
            get {
                return ResourceManager.GetString("bonuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to categories.
        /// </summary>
        public static string categories {
            get {
                return ResourceManager.GetString("categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collect all your achievements.
        /// </summary>
        public static string collect_all_your_achieves {
            get {
                return ResourceManager.GetString("collect_all_your_achieves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter code.
        /// </summary>
        public static string enter_code {
            get {
                return ResourceManager.GetString("enter_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login using .
        /// </summary>
        public static string enter_using_facebook {
            get {
                return ResourceManager.GetString("enter_using_facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook signup.
        /// </summary>
        public static string facebook_singup {
            get {
                return ResourceManager.GetString("facebook_singup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://itsbeta.com.
        /// </summary>
        public static string itsbeta_url {
            get {
                return ResourceManager.GetString("itsbeta_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last.
        /// </summary>
        public static string last {
            get {
                return ResourceManager.GetString("last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loading....
        /// </summary>
        public static string loading {
            get {
                return ResourceManager.GetString("loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data.
        /// </summary>
        public static string no_data {
            get {
                return ResourceManager.GetString("no_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to profile.
        /// </summary>
        public static string profile {
            get {
                return ResourceManager.GetString("profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR-READER.
        /// </summary>
        public static string qr_reader {
            get {
                return ResourceManager.GetString("qr_reader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate application.
        /// </summary>
        public static string rate_app {
            get {
                return ResourceManager.GetString("rate_app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send email.
        /// </summary>
        public static string send_email {
            get {
                return ResourceManager.GetString("send_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string statistics {
            get {
                return ResourceManager.GetString("statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subcategories:.
        /// </summary>
        public static string subcategories {
            get {
                return ResourceManager.GetString("subcategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use code or QR-reader.
        /// </summary>
        public static string use_code_or_qr_description {
            get {
                return ResourceManager.GetString("use_code_or_qr_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use QR-reader.
        /// </summary>
        public static string use_qr_reader {
            get {
                return ResourceManager.GetString("use_qr_reader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to years.
        /// </summary>
        public static string years {
            get {
                return ResourceManager.GetString("years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to years.
        /// </summary>
        public static string years1 {
            get {
                return ResourceManager.GetString("years1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to years.
        /// </summary>
        public static string years234 {
            get {
                return ResourceManager.GetString("years234", resourceCulture);
            }
        }
    }
}
