#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("itsbeta.achievements.Resource", IsApplication=true)]

namespace itsbeta.achievements
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Novell.MonoDroid.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int back = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int BlueBtn_norm = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int BlueBtn_press = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Btn_divider_v = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Categories_btn_arrow = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Categories_btn_divider = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Categories_btn_norm = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Categories_btn_press = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Categories_popup_background = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Categories_popup_bottom = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Categories_popup_check = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int DarkBlueBtn_norm = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int DarkBlueBtn_press = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int FB_icon = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int FB_logo = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int GreenBtn_norm = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int GreenBtn_press = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int line = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int Login_background = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int Login_background2 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int Login_BigBadge = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int NavBar_icon_exit_norm = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int NavBar_icon_exit_press = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int NavBar_icon_plus_norm = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int NavBar_icon_plus_press = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int NavBar_icon_profile_norm = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int NavBar_icon_profile_press = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int NavBar_leftWindow = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int NavBar_screen_icon = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int NavBar_screen_left = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int NavBar_screen_middle = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int NavBar_screen_right = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int Navigation_bar = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int Paper_background_bottomLeft = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int Paper_background_bottomLeft_press = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int Paper_background_bottomMiddle = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int Paper_background_bottomMiddle_press = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int Paper_background_bottomRight = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int Paper_background_bottomRight_press = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int Paper_background_middleLeft = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int Paper_background_middleLeft_press = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int Paper_background_middleMiddle = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int Paper_background_middleMiddle_press = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int Paper_background_middleRight = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int Paper_background_middleRight_press = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int Paper_background_topLeft = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int Paper_background_topMiddle = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int Paper_background_topRight = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int Paper_BadgeShape = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int Paper_Divider_blue = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int Paper_Divider_green = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int Paper_Divider_violet = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int Paper_icon_close_norm = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int Paper_icon_close_press = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int Paper_shadow = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int Profile_StatisticPreview_blue = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int Profile_StatisticPreview_green = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int Profile_StatisticPreview_violet = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int Profile_StatusBar_active = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int Profile_StatusBar_norm = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int profilescr_titleback = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int Table_lable_blue_left = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int Table_lable_blue_middle = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int Table_lable_blue_right = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int Table_lable_green_left = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int Table_lable_green_middle = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int Table_lable_green_right = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int Table_lable_violet_left = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int Table_lable_violet_middle = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int Table_lable_violet_right = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int TableAndButtons_divider_h = 2130837574;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060058
			public const int AchiveDescriptionTextView = 2131099736;
			
			// aapt resource value: 0x7f060054
			public const int AchiveImageView = 2131099732;
			
			// aapt resource value: 0x7f060057
			public const int AchiveNameTextView = 2131099735;
			
			// aapt resource value: 0x7f060055
			public const int AchiveReceiveDateTextView = 2131099733;
			
			// aapt resource value: 0x7f06002b
			public const int BadgeImageView = 2131099691;
			
			// aapt resource value: 0x7f060002
			public const int BadgeSheetImageView = 2131099650;
			
			// aapt resource value: 0x7f060022
			public const int BadgeSheet_CloseImageButton = 2131099682;
			
			// aapt resource value: 0x7f060021
			public const int BadgeSheet_CloseImageButtonFake = 2131099681;
			
			// aapt resource value: 0x7f06005b
			public const int BonusImageView_left = 2131099739;
			
			// aapt resource value: 0x7f060059
			public const int BonusImageView_right = 2131099737;
			
			// aapt resource value: 0x7f06005c
			public const int BonusTextView = 2131099740;
			
			// aapt resource value: 0x7f06005d
			public const int Bonus_DiscountImageView_left = 2131099741;
			
			// aapt resource value: 0x7f06005a
			public const int Bonus_DiscountImageView_right = 2131099738;
			
			// aapt resource value: 0x7f06005e
			public const int Bonus_DiscountTextView = 2131099742;
			
			// aapt resource value: 0x7f060060
			public const int Bonus_GiftImageView_left = 2131099744;
			
			// aapt resource value: 0x7f06005f
			public const int Bonus_GiftImageView_right = 2131099743;
			
			// aapt resource value: 0x7f060061
			public const int Bonus_GiftTextView = 2131099745;
			
			// aapt resource value: 0x7f060051
			public const int CategNameTextView = 2131099729;
			
			// aapt resource value: 0x7f060052
			public const int CheckImageView = 2131099730;
			
			// aapt resource value: 0x7f060001
			public const int FirstBadgeFrontRelativeLayout = 2131099649;
			
			// aapt resource value: 0x7f06001f
			public const int FirstBadge_GreenBonusImageView = 2131099679;
			
			// aapt resource value: 0x7f060020
			public const int FirstBadge_ProfileNameTextView = 2131099680;
			
			// aapt resource value: 0x7f060000
			public const int FristBadgeMainRelativeLayout = 2131099648;
			
			// aapt resource value: 0x7f06001c
			public const int NavBar_AchievesCountTextView = 2131099676;
			
			// aapt resource value: 0x7f06001b
			public const int NavBar_GlobedImageView = 2131099675;
			
			// aapt resource value: 0x7f060019
			public const int NavBar_ImageButton = 2131099673;
			
			// aapt resource value: 0x7f060049
			public const int NavBar_addcodeImageButton = 2131099721;
			
			// aapt resource value: 0x7f06004b
			public const int NavBar_addcodeImageButtonFake = 2131099723;
			
			// aapt resource value: 0x7f060005
			public const int addbadge_addcodeButton = 2131099653;
			
			// aapt resource value: 0x7f060003
			public const int addbadge_cancelButton = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int addbadge_readQRButton = 2131099652;
			
			// aapt resource value: 0x7f060015
			public const int addcode_autoCompleteTextView = 2131099669;
			
			// aapt resource value: 0x7f060013
			public const int addcode_cancelButton = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int addcode_readyButton = 2131099668;
			
			// aapt resource value: 0x7f060009
			public const int badgewin_BadgeImageView = 2131099657;
			
			// aapt resource value: 0x7f06000f
			public const int badgewin_CloseImageButton = 2131099663;
			
			// aapt resource value: 0x7f06000e
			public const int badgewin_CloseImageButtonFake = 2131099662;
			
			// aapt resource value: 0x7f06000a
			public const int badgewin_GreenBonusImageView = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int badgewin_badgeTextView = 2131099659;
			
			// aapt resource value: 0x7f060011
			public const int badgewin_bonusdescrTextView = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int badgewin_categ_projectTextView = 2131099666;
			
			// aapt resource value: 0x7f060010
			public const int badgewin_greenbonusTextView = 2131099664;
			
			// aapt resource value: 0x7f06000c
			public const int badgewin_howwonderTextView = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int badgewin_wonderdescrTextView = 2131099661;
			
			// aapt resource value: 0x7f060008
			public const int center = 2131099656;
			
			// aapt resource value: 0x7f060053
			public const int check_button = 2131099731;
			
			// aapt resource value: 0x7f060026
			public const int dropdownachor = 2131099686;
			
			// aapt resource value: 0x7f060007
			public const int imageView1 = 2131099655;
			
			// aapt resource value: 0x7f060017
			public const int imageView2 = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int imageView3 = 2131099672;
			
			// aapt resource value: 0x7f060042
			public const int linearLayout1 = 2131099714;
			
			// aapt resource value: 0x7f06002a
			public const int login = 2131099690;
			
			// aapt resource value: 0x7f06002d
			public const int loginWebView = 2131099693;
			
			// aapt resource value: 0x7f060028
			public const int login_backgroundImageView = 2131099688;
			
			// aapt resource value: 0x7f060027
			public const int login_centerTextView = 2131099687;
			
			// aapt resource value: 0x7f06002c
			public const int login_signinTextView = 2131099692;
			
			// aapt resource value: 0x7f06001e
			public const int paper_BadgeImageView = 2131099678;
			
			// aapt resource value: 0x7f060041
			public const int profilescr_CategNameTextView = 2131099713;
			
			// aapt resource value: 0x7f06002e
			public const int profilescr_NavBar_LogoutImageButton = 2131099694;
			
			// aapt resource value: 0x7f06003c
			public const int profilescr_ProjectNameTextView = 2131099708;
			
			// aapt resource value: 0x7f060036
			public const int profilescr_allBadgesImageView = 2131099702;
			
			// aapt resource value: 0x7f060038
			public const int profilescr_allBadgesTextView = 2131099704;
			
			// aapt resource value: 0x7f060039
			public const int profilescr_allbadgescountTextView = 2131099705;
			
			// aapt resource value: 0x7f06003a
			public const int profilescr_bonusCountTextView = 2131099706;
			
			// aapt resource value: 0x7f060035
			public const int profilescr_bonusImageView = 2131099701;
			
			// aapt resource value: 0x7f060031
			public const int profilescr_linearLayout = 2131099697;
			
			// aapt resource value: 0x7f060040
			public const int profilescr_parentrelativeLayout = 2131099712;
			
			// aapt resource value: 0x7f06002f
			public const int profilescr_profiletextView = 2131099695;
			
			// aapt resource value: 0x7f060034
			public const int profilescr_statTextView = 2131099700;
			
			// aapt resource value: 0x7f06003d
			public const int profilescr_statbarImageViewNorm = 2131099709;
			
			// aapt resource value: 0x7f06003f
			public const int profilescr_statbarImageViewwActive = 2131099711;
			
			// aapt resource value: 0x7f060037
			public const int profilescr_subcatImageView = 2131099703;
			
			// aapt resource value: 0x7f06003b
			public const int profilescr_subcategCountTextView = 2131099707;
			
			// aapt resource value: 0x7f060033
			public const int profilescr_userAgelocTextView = 2131099699;
			
			// aapt resource value: 0x7f060032
			public const int profilescr_usernameTextView = 2131099698;
			
			// aapt resource value: 0x7f060044
			public const int qrcodereader_readyButton = 2131099716;
			
			// aapt resource value: 0x7f060043
			public const int qrcodereaderscr_cancelButton = 2131099715;
			
			// aapt resource value: 0x7f060046
			public const int qrreader_camerasurfaceView = 2131099718;
			
			// aapt resource value: 0x7f060025
			public const int relativeLayout1 = 2131099685;
			
			// aapt resource value: 0x7f060056
			public const int relativeLayout2 = 2131099734;
			
			// aapt resource value: 0x7f060030
			public const int scrollView1 = 2131099696;
			
			// aapt resource value: 0x7f06004d
			public const int secaondscr_faketextView = 2131099725;
			
			// aapt resource value: 0x7f06004f
			public const int secondscr_CategNameRowTextView = 2131099727;
			
			// aapt resource value: 0x7f06001a
			public const int secondscr_NavBar_LeftWinImageView = 2131099674;
			
			// aapt resource value: 0x7f06001d
			public const int secondscr_NavBar_ProfileScreenImageButton = 2131099677;
			
			// aapt resource value: 0x7f06004a
			public const int secondscr_NavBar_ProfileScreenImageButtonFake = 2131099722;
			
			// aapt resource value: 0x7f060047
			public const int secondscr_categoriesbar_linearLayout = 2131099719;
			
			// aapt resource value: 0x7f060050
			public const int secondscr_categoryrowDividerImageView = 2131099728;
			
			// aapt resource value: 0x7f06004e
			public const int secondscr_categrowrelativeLayout = 2131099726;
			
			// aapt resource value: 0x7f06004c
			public const int secondscr_linearLayoutInactive = 2131099724;
			
			// aapt resource value: 0x7f060048
			public const int secondscr_listView = 2131099720;
			
			// aapt resource value: 0x7f060029
			public const int signUpTextView = 2131099689;
			
			// aapt resource value: 0x7f06003e
			public const int statbarlinearLayout = 2131099710;
			
			// aapt resource value: 0x7f060045
			public const int textView = 2131099717;
			
			// aapt resource value: 0x7f060006
			public const int textView1 = 2131099654;
			
			// aapt resource value: 0x7f060016
			public const int textView2 = 2131099670;
			
			// aapt resource value: 0x7f060023
			public const int textView3 = 2131099683;
			
			// aapt resource value: 0x7f060024
			public const int textView5 = 2131099684;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddBadgeMenuLayoutLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int BadgeWindowActivityLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int EnterCodeLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int FirstBadgeActivityLayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int InactiveBackgroundLayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int LoginActivityLayout = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int LoginWebLayout = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int ProfileScreenActivityLayout = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int ProfileScreenChildRow = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int ProfileScreenParentRow = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int QRReaderActivityLayout = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int SecondScreenActivityLayout = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int SecondScreenCategoryRow = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int SecondScreenDropDownListRow = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int SecondScreenListRow = 2130903054;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int FullHeightDialog = 2131034112;
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
