#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("itsbeta.achievements.Resource", IsApplication=true)]

namespace itsbeta.achievements
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues ();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int back = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int BlueBtn_norm = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int BlueBtn_press = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Btn_divider_v = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Categories_btn_arrow = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Categories_btn_divider = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Categories_btn_norm = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Categories_btn_press = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Categories_popup_background = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Categories_popup_bottom = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Categories_popup_check = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int DarkBlueBtn_norm = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int DarkBlueBtn_press = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int entercodeactive = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int FB_icon = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int FB_logo = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int GreenBtn_norm = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int GreenBtn_press = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int Icon_128 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int icon_bonuses = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int icon_discounts = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int icon_gifts = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int line = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int line_blue = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int Login_background = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int Login_background2 = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int Login_BigBadge = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int NavBar_icon_exit_norm = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int NavBar_icon_exit_press = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int NavBar_icon_plus_norm = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int NavBar_icon_plus_press = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int NavBar_icon_profile_norm = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int NavBar_icon_profile_press = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int NavBar_icon_refresh = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int NavBar_icon_refresh_norm = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int NavBar_leftWindow = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int NavBar_screen_icon = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int NavBar_screen_left = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int NavBar_screen_middle = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int NavBar_screen_right = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int Navigation_bar = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int Paper_background_bottomLeft = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int Paper_background_bottomLeft_press = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int Paper_background_bottomMiddle = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int Paper_background_bottomMiddle_press = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int Paper_background_bottomRight = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int Paper_background_bottomRight_press = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int Paper_background_middleLeft = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int Paper_background_middleLeft_press = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int Paper_background_middleMiddle = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int Paper_background_middleMiddle_press = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int Paper_background_middleRight = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int Paper_background_middleRight_press = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int Paper_background_topLeft = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int Paper_background_topMiddle = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int Paper_background_topRight = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int Paper_BadgeShape = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int Paper_Divider_blue = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int Paper_Divider_green = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int Paper_Divider_violet = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int Paper_icon_close_norm = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int Paper_icon_close_press = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int Paper_shadow = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int Preloader_panel_left = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int Preloader_panel_middle = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int Preloader_panel_right = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int Profile_StatisticPreview_blue = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int Profile_StatisticPreview_green = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int Profile_StatisticPreview_violet = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int Profile_StatusBar_active = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int Profile_StatusBar_norm = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int profilescr_titleback = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int Splash_logo = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int Table_lable_blue_left = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int Table_lable_blue_middle = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int Table_lable_blue_right = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int Table_lable_green_left = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int Table_lable_green_middle = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int Table_lable_green_right = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int Table_lable_violet_left = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int Table_lable_violet_middle = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int Table_lable_violet_right = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int TableAndButtons_divider_h = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int trans = 2130837587;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05007a
			public const int AchiveDescriptionTextView = 2131034234;
			
			// aapt resource value: 0x7f050076
			public const int AchiveImageView = 2131034230;
			
			// aapt resource value: 0x7f050079
			public const int AchiveNameTextView = 2131034233;
			
			// aapt resource value: 0x7f050077
			public const int AchiveReceiveDateTextView = 2131034231;
			
			// aapt resource value: 0x7f05003b
			public const int BadgeImageView = 2131034171;
			
			// aapt resource value: 0x7f050002
			public const int BadgeSheetImageView = 2131034114;
			
			// aapt resource value: 0x7f050082
			public const int BonusCenterImageView = 2131034242;
			
			// aapt resource value: 0x7f05007d
			public const int BonusImageView_left = 2131034237;
			
			// aapt resource value: 0x7f05007c
			public const int BonusImageView_right = 2131034236;
			
			// aapt resource value: 0x7f050084
			public const int Bonus_DiscountCenterImageView = 2131034244;
			
			// aapt resource value: 0x7f05007f
			public const int Bonus_DiscountImageView_left = 2131034239;
			
			// aapt resource value: 0x7f05007e
			public const int Bonus_DiscountImageView_right = 2131034238;
			
			// aapt resource value: 0x7f050083
			public const int Bonus_GiftCenterImageView = 2131034243;
			
			// aapt resource value: 0x7f050081
			public const int Bonus_GiftImageView_left = 2131034241;
			
			// aapt resource value: 0x7f050080
			public const int Bonus_GiftImageView_right = 2131034240;
			
			// aapt resource value: 0x7f050073
			public const int CategNameTextView = 2131034227;
			
			// aapt resource value: 0x7f050074
			public const int CheckImageView = 2131034228;
			
			// aapt resource value: 0x7f050001
			public const int FirstBadgeFrontRelativeLayout = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int FristBadgeMainRelativeLayout = 2131034112;
			
			// aapt resource value: 0x7f05002b
			public const int NavBar_AchievesCountTextView = 2131034155;
			
			// aapt resource value: 0x7f05002a
			public const int NavBar_GlobedImageView = 2131034154;
			
			// aapt resource value: 0x7f050028
			public const int NavBar_ImageButton = 2131034152;
			
			// aapt resource value: 0x7f05006a
			public const int NavBar_addcodeImageButton = 2131034218;
			
			// aapt resource value: 0x7f05006d
			public const int NavBar_addcodeImageButtonFake = 2131034221;
			
			// aapt resource value: 0x7f050009
			public const int RelativeLayout = 2131034121;
			
			// aapt resource value: 0x7f050005
			public const int addbadge_addcodeButton = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int addbadge_cancelButton = 2131034115;
			
			// aapt resource value: 0x7f050008
			public const int addbadge_hintTextView = 2131034120;
			
			// aapt resource value: 0x7f050004
			public const int addbadge_readQRButton = 2131034116;
			
			// aapt resource value: 0x7f050021
			public const int addcode_autoCompleteTextView = 2131034145;
			
			// aapt resource value: 0x7f05001f
			public const int addcode_cancelButton = 2131034143;
			
			// aapt resource value: 0x7f050020
			public const int addcode_readyButton = 2131034144;
			
			// aapt resource value: 0x7f05000c
			public const int badgewin_BadgeImageView = 2131034124;
			
			// aapt resource value: 0x7f05000f
			public const int badgewin_BadgeImageViewShadow = 2131034127;
			
			// aapt resource value: 0x7f050019
			public const int badgewin_BlueBonusImageView = 2131034137;
			
			// aapt resource value: 0x7f050015
			public const int badgewin_CloseImageButton = 2131034133;
			
			// aapt resource value: 0x7f050014
			public const int badgewin_CloseImageButtonFake = 2131034132;
			
			// aapt resource value: 0x7f050017
			public const int badgewin_GreenBonusImageView = 2131034135;
			
			// aapt resource value: 0x7f050018
			public const int badgewin_VioletBonusImageView = 2131034136;
			
			// aapt resource value: 0x7f050010
			public const int badgewin_badgeTextView = 2131034128;
			
			// aapt resource value: 0x7f05001d
			public const int badgewin_bluedescbackgroundImageView = 2131034141;
			
			// aapt resource value: 0x7f05001a
			public const int badgewin_bonusTextView = 2131034138;
			
			// aapt resource value: 0x7f05001c
			public const int badgewin_bonusdescrTextView = 2131034140;
			
			// aapt resource value: 0x7f050016
			public const int badgewin_categ_projectTextView = 2131034134;
			
			// aapt resource value: 0x7f050013
			public const int badgewin_detailsTextView = 2131034131;
			
			// aapt resource value: 0x7f05001b
			public const int badgewin_greendescbackgroundImageView = 2131034139;
			
			// aapt resource value: 0x7f050011
			public const int badgewin_howwonderTextView = 2131034129;
			
			// aapt resource value: 0x7f05000a
			public const int badgewin_scrollView = 2131034122;
			
			// aapt resource value: 0x7f05001e
			public const int badgewin_violetdescbackgroundImageView = 2131034142;
			
			// aapt resource value: 0x7f050012
			public const int badgewin_wonderdescrTextView = 2131034130;
			
			// aapt resource value: 0x7f050078
			public const int bonusesColumn_linearLayout = 2131034232;
			
			// aapt resource value: 0x7f05007b
			public const int bonuslist_relativeLayout = 2131034235;
			
			// aapt resource value: 0x7f05000d
			public const int bonuspaperlist_linearLayout = 2131034125;
			
			// aapt resource value: 0x7f050027
			public const int cancelButton = 2131034151;
			
			// aapt resource value: 0x7f050070
			public const int categoriesListDownShadowImageView = 2131034224;
			
			// aapt resource value: 0x7f05006f
			public const int categorieslistView = 2131034223;
			
			// aapt resource value: 0x7f05000e
			public const int center = 2131034126;
			
			// aapt resource value: 0x7f050075
			public const int check_button = 2131034229;
			
			// aapt resource value: 0x7f050036
			public const int dropdownachor = 2131034166;
			
			// aapt resource value: 0x7f05002e
			public const int firstbadgewin_BadgeImageView = 2131034158;
			
			// aapt resource value: 0x7f05002f
			public const int firstbadgewin_BadgeImageViewShadow = 2131034159;
			
			// aapt resource value: 0x7f050034
			public const int firstbadgewin_CloseImageButton = 2131034164;
			
			// aapt resource value: 0x7f050033
			public const int firstbadgewin_CloseImageButtonFake = 2131034163;
			
			// aapt resource value: 0x7f050031
			public const int firstbadgewin_howTextView = 2131034161;
			
			// aapt resource value: 0x7f050030
			public const int firstbadgewin_usernameTextView = 2131034160;
			
			// aapt resource value: 0x7f050032
			public const int firstbadgewin_wonderdescrTextView = 2131034162;
			
			// aapt resource value: 0x7f050007
			public const int imageView1 = 2131034119;
			
			// aapt resource value: 0x7f050023
			public const int imageView2 = 2131034147;
			
			// aapt resource value: 0x7f050024
			public const int imageView3 = 2131034148;
			
			// aapt resource value: 0x7f050052
			public const int imageView4 = 2131034194;
			
			// aapt resource value: 0x7f050053
			public const int imageView5 = 2131034195;
			
			// aapt resource value: 0x7f050054
			public const int imageView6 = 2131034196;
			
			// aapt resource value: 0x7f050055
			public const int imageView7 = 2131034197;
			
			// aapt resource value: 0x7f050025
			public const int linearLayout1 = 2131034149;
			
			// aapt resource value: 0x7f05003e
			public const int listView1 = 2131034174;
			
			// aapt resource value: 0x7f05003a
			public const int login = 2131034170;
			
			// aapt resource value: 0x7f05003d
			public const int loginWebView = 2131034173;
			
			// aapt resource value: 0x7f050037
			public const int login_backgroundImageView = 2131034167;
			
			// aapt resource value: 0x7f050038
			public const int login_centerTextView = 2131034168;
			
			// aapt resource value: 0x7f05003c
			public const int login_signinTextView = 2131034172;
			
			// aapt resource value: 0x7f050050
			public const int profilescr_CategNameTextView = 2131034192;
			
			// aapt resource value: 0x7f05003f
			public const int profilescr_NavBar_LogoutImageButton = 2131034175;
			
			// aapt resource value: 0x7f05004e
			public const int profilescr_ProjectNameTextView = 2131034190;
			
			// aapt resource value: 0x7f050047
			public const int profilescr_allBadgesImageView = 2131034183;
			
			// aapt resource value: 0x7f050049
			public const int profilescr_allBadgesTextView = 2131034185;
			
			// aapt resource value: 0x7f05004b
			public const int profilescr_allbadgescountTextView = 2131034187;
			
			// aapt resource value: 0x7f05004c
			public const int profilescr_bonusCountTextView = 2131034188;
			
			// aapt resource value: 0x7f050046
			public const int profilescr_bonusImageView = 2131034182;
			
			// aapt resource value: 0x7f050042
			public const int profilescr_linearLayout = 2131034178;
			
			// aapt resource value: 0x7f050041
			public const int profilescr_logiutbuttonfake = 2131034177;
			
			// aapt resource value: 0x7f05004f
			public const int profilescr_parentrelativeLayout = 2131034191;
			
			// aapt resource value: 0x7f050040
			public const int profilescr_profiletextView = 2131034176;
			
			// aapt resource value: 0x7f050045
			public const int profilescr_statTextView = 2131034181;
			
			// aapt resource value: 0x7f050048
			public const int profilescr_subcatImageView = 2131034184;
			
			// aapt resource value: 0x7f05004d
			public const int profilescr_subcategCountTextView = 2131034189;
			
			// aapt resource value: 0x7f050044
			public const int profilescr_userAgelocTextView = 2131034180;
			
			// aapt resource value: 0x7f050043
			public const int profilescr_usernameTextView = 2131034179;
			
			// aapt resource value: 0x7f050051
			public const int progressDialogMessageTextView = 2131034193;
			
			// aapt resource value: 0x7f050072
			public const int projectsListDownShadowImageView = 2131034226;
			
			// aapt resource value: 0x7f050071
			public const int projectslistView = 2131034225;
			
			// aapt resource value: 0x7f050056
			public const int qrreader_codetextView = 2131034198;
			
			// aapt resource value: 0x7f050026
			public const int readyButton = 2131034150;
			
			// aapt resource value: 0x7f050059
			public const int recbadgewin_BadgeImageView = 2131034201;
			
			// aapt resource value: 0x7f05005a
			public const int recbadgewin_BadgeImageViewShadow = 2131034202;
			
			// aapt resource value: 0x7f05005f
			public const int recbadgewin_CloseImageButton = 2131034207;
			
			// aapt resource value: 0x7f05005e
			public const int recbadgewin_CloseImageButtonFake = 2131034206;
			
			// aapt resource value: 0x7f05005b
			public const int recbadgewin_badgeTextView = 2131034203;
			
			// aapt resource value: 0x7f05005c
			public const int recbadgewin_howwonderTextView = 2131034204;
			
			// aapt resource value: 0x7f050058
			public const int recbadgewin_inactiveButton = 2131034200;
			
			// aapt resource value: 0x7f050057
			public const int recbadgewin_scrollView = 2131034199;
			
			// aapt resource value: 0x7f05005d
			public const int recbadgewin_wonderdescrTextView = 2131034205;
			
			// aapt resource value: 0x7f05000b
			public const int relativeLayout1 = 2131034123;
			
			// aapt resource value: 0x7f050035
			public const int relativeLayout2 = 2131034165;
			
			// aapt resource value: 0x7f05002d
			public const int scrollView1 = 2131034157;
			
			// aapt resource value: 0x7f05006e
			public const int secaondscr_faketextView = 2131034222;
			
			// aapt resource value: 0x7f050063
			public const int secondscr_CategNameRowTextView = 2131034211;
			
			// aapt resource value: 0x7f050029
			public const int secondscr_NavBar_LeftWinImageView = 2131034153;
			
			// aapt resource value: 0x7f05002c
			public const int secondscr_NavBar_ProfileScreenImageButton = 2131034156;
			
			// aapt resource value: 0x7f05006b
			public const int secondscr_NavBar_ProfileScreenImageButtonFake = 2131034219;
			
			// aapt resource value: 0x7f050060
			public const int secondscr_NavBar_RefreshImageButton = 2131034208;
			
			// aapt resource value: 0x7f05006c
			public const int secondscr_NavBar_RefreshImageButtonFake = 2131034220;
			
			// aapt resource value: 0x7f050061
			public const int secondscr_categoriesbar_linearLayout = 2131034209;
			
			// aapt resource value: 0x7f050064
			public const int secondscr_categoryrowDividerImageView = 2131034212;
			
			// aapt resource value: 0x7f050062
			public const int secondscr_categrowrelativeLayout = 2131034210;
			
			// aapt resource value: 0x7f050069
			public const int secondscr_inactiveAllButton = 2131034217;
			
			// aapt resource value: 0x7f050068
			public const int secondscr_inactiveListButton = 2131034216;
			
			// aapt resource value: 0x7f050067
			public const int secondscr_listView = 2131034215;
			
			// aapt resource value: 0x7f050066
			public const int secondscr_projectNameRowTextView = 2131034214;
			
			// aapt resource value: 0x7f050065
			public const int secondscr_projectsrelativeLayout = 2131034213;
			
			// aapt resource value: 0x7f050039
			public const int signUpTextView = 2131034169;
			
			// aapt resource value: 0x7f050006
			public const int textView1 = 2131034118;
			
			// aapt resource value: 0x7f050022
			public const int textView2 = 2131034146;
			
			// aapt resource value: 0x7f05004a
			public const int textView3 = 2131034186;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int addbadgemenulayoutlayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int badgewindowactivitylayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int bonusonlistrowlayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int entercodelayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int exitdialoglayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int firstbadgeactivitylayout = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int firstbadgeactivityloadinglayout = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int loginactivitylayout = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int loginweblayout = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int popuplistlayout = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int profilescreenactivitylayout = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int profilescreenchildrow = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int profilescreenparentrow = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int progressdialoglayout = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int qrreaderlayout = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int receivebadgelayount = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int secondscreenactivitylayout = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int secondscreencategoryrow = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int secondscreendropdownlistrow = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int secondscreenlistrow = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int secondscreenlistrowll = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int splashactivitylayout = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int wrongcodedialoglayout = 2130903062;
			
			private Layout()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f040000
			public const int FullHeightDialog = 2130968576;
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
